# .github/workflows/manual-docker-build.yml

name: Manual Docker Build and Push

# (新增) 为工作流设置权限
# 推送到 GHCR 需要 packages: write 权限
permissions:
  contents: read
  packages: write

on:
  workflow_dispatch:
    inputs:
      dockerfile_path:
        description: 'Dockerfile 在仓库中的路径'
        required: true
        type: string
        default: 'docker-list/proxy.Dockerfile'
      
      image_name:
        description: '镜像名称 (不包含仓库地址, e.g., my-proxy-app)'
        required: true
        type: string
        default: 'my-proxy-app'

      image_tag:
        description: '镜像的标签 (e.g., latest, v1.0)'
        required: true
        type: string
        default: 'latest'
      
      # (新增) 布尔值输入，会显示为复选框
      push_to_dockerhub:
        description: '☑️ 推送到 Docker Hub'
        required: true
        type: boolean
        default: true

      push_to_ghcr:
        description: '☑️ 推送到 GitHub Registry (ghcr.io)'
        required: true
        type: boolean
        default: false

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      # (修改) 登录到 Docker Hub (条件执行)
      - name: Login to Docker Hub
        if: inputs.push_to_dockerhub == true
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      # (新增) 登录到 GitHub Container Registry (ghcr.io) (条件执行)
      - name: Login to GitHub Container Registry
        if: inputs.push_to_ghcr == true
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          # GITHUB_TOKEN 是由 GitHub Actions 自动创建的
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        
      # (新增) 动态生成镜像标签
      - name: Generate tags
        id: tags
        run: |
          TAGS=""
          if [ "${{ inputs.push_to_dockerhub }}" == "true" ]; then
            TAGS="${TAGS}${{ secrets.DOCKERHUB_USERNAME }}/${{ inputs.image_name }}:${{ inputs.image_tag }}\n"
          fi
          if [ "${{ inputs.push_to_ghcr }}" == "true" ]; then
            TAGS="${TAGS}ghcr.io/${{ github.repository_owner }}/${{ inputs.image_name }}:${{ inputs.image_tag }}\n"
          fi
          echo "tags=$TAGS" >> $GITHUB_OUTPUT

      # (修改) 构建并推送到选择的仓库
      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ${{ inputs.dockerfile_path }}
          push: true
          # 使用上一步生成的标签
          tags: ${{ steps.tags.outputs.tags }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
